# Домашнее задание
1. Загрузить выборку `car.csv`
2. В качестве упражнения выведите на экран название (Make) марки и (Model) модель входит в интервал год выпуска (Year) с 2013 по 2015
3. Выводим первый и третий столбцы, сначала по отдельности, потом вместе.
4. Вывести 10 первых строк, вывести 23 случайных строк.
5. Вывести статистику по числовым показателям
6. Сгрупировать данные по столбцу Make, Year

In [1]:
import pandas as pd
import numpy as np

__Загрузить выборку car.csv__

In [2]:
data=pd.read_csv('../dataset/car.csv', delimiter=',')
data

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [3]:
data.shape

(11914, 16)

In [4]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

__В качестве упражнения выведите на экран название (Make) марки и (Model) модель входит в интервал год выпуска (Year) с 2013 по 2015__

In [5]:
# фильтруем данные по условию года выпуска
filtered_data = data[(data['Year'] >= 2013) & (data['Year'] <= 2015)]
# выбираем только столбцы "Make" и "Model"
filtered_data[['Make', 'Model']]

        Make     Model
9        BMW  1 Series
10       BMW  1 Series
11       BMW  1 Series
12       BMW  1 Series
13       BMW  1 Series
...      ...       ...
11896    BMW        Z4
11897    BMW        Z4
11898    BMW        Z4
11899    BMW        Z4
11912  Acura       ZDX

[3125 rows x 2 columns]

__Выводим первый и третий столбцы, сначала по отдельности, потом вместе.__

In [6]:
data.iloc[:,1]

0        1 Series M
1          1 Series
2          1 Series
3          1 Series
4          1 Series
            ...
11909           ZDX
11910           ZDX
11911           ZDX
11912           ZDX
11913        Zephyr
Name: Model, Length: 11914, dtype: object

In [7]:
data.iloc[:,3]

0           premium unleaded (required)
1           premium unleaded (required)
2           premium unleaded (required)
3           premium unleaded (required)
4           premium unleaded (required)
                      ...
11909       premium unleaded (required)
11910       premium unleaded (required)
11911       premium unleaded (required)
11912    premium unleaded (recommended)
11913                  regular unleaded
Name: Engine Fuel Type, Length: 11914, dtype: object

In [8]:
data.iloc[:,[1,3]]

            Model                Engine Fuel Type
0      1 Series M     premium unleaded (required)
1        1 Series     premium unleaded (required)
2        1 Series     premium unleaded (required)
3        1 Series     premium unleaded (required)
4        1 Series     premium unleaded (required)
...           ...                             ...
11909         ZDX     premium unleaded (required)
11910         ZDX     premium unleaded (required)
11911         ZDX     premium unleaded (required)
11912         ZDX  premium unleaded (recommended)
11913      Zephyr                regular unleaded

[11914 rows x 2 columns]

Вывести 10 первых строк, вывести 23 случайных строк.

In [9]:
data.iloc[:10,:]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
5,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,31200
6,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,26,17,3916,44100
7,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,39300
8,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,36900
9,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,27,18,3916,37200

In [10]:
randIdx = np.random.randint(data.shape[0], size=25)
data.iloc[randIdx,:]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
2135,Volkswagen,Cabrio,2001,regular unleaded,115.0,4.0,MANUAL,front wheel drive,2.0,NaN,Compact,Convertible,28,21,873,20600
4190,Ford,Escape Hybrid,2011,regular unleaded,177.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hybrid",Compact,4dr SUV,27,30,5657,32320
10037,Chevrolet,Suburban,2015,flex-fuel (unleaded/E85),355.0,8.0,AUTOMATIC,four wheel drive,4.0,"Flex Fuel,Performance",Large,4dr SUV,22,15,1385,66785
7669,Toyota,Prius c,2015,regular unleaded,99.0,4.0,AUTOMATIC,front wheel drive,4.0,"Hatchback,Hybrid",Compact,4dr Hatchback,46,53,2031,19540
10900,Audi,TTS,2015,premium unleaded (required),265.0,4.0,AUTOMATED_MANUAL,all wheel drive,2.0,"Factory Tuner,Luxury,Performance",Compact,Coupe,31,22,3105,48700
5297,Mercedes-Benz,GLA-Class,2015,premium unleaded (required),208.0,4.0,AUTOMATED_MANUAL,front wheel drive,4.0,"Crossover,Luxury",Compact,4dr SUV,35,25,617,31300
3354,Mazda,CX-5,2014,regular unleaded,184.0,4.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,30,24,586,26065
6514,Ford,LTD Crown Victoria,1990,regular unleaded,150.0,8.0,AUTOMATIC,rear wheel drive,4.0,NaN,Large,Wagon,22,15,5657,2000
1413,Nissan,Altima,2016,regular unleaded,182.0,4.0,AUTOMATIC,front wheel drive,4.0,NaN,Midsize,Sedan,39,27,2009,22900
10538,Volkswagen,Touareg,2015,premium unleaded (recommended),380.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hybrid",Midsize,4dr SUV,24,20,873,66995
6479,Lexus,LS 460,2015,premium unleaded (required),360.0,8.0,AUTOMATIC,all wheel drive,4.0,"Luxury,Performance",Large,Sedan,23,16,454,82305
11008,Toyota,Tundra,2016,regular unleaded,381.0,8.0,AUTOMATIC,rear wheel drive,4.0,NaN,Large,Extended Cab Pickup,18,13,2031,32650
1251,Honda,Accord,2016,regular unleaded,185.0,4.0,AUTOMATIC,front wheel drive,2.0,NaN,Midsize,Coupe,35,26,2202,25725
3289,Nissan,Cube,2013,regular unleaded,122.0,4.0,MANUAL,front wheel drive,4.0,NaN,Compact,Wagon,30,25,2009,16760
8181,Dodge,Ram Pickup 1500,2009,flex-fuel (unleaded/E85),310.0,8.0,AUTOMATIC,four wheel drive,4.0,Flex Fuel,Large,Crew Cab Pickup,18,13,1851,32945
6584,Infiniti,M30,1991,regular unleaded,162.0,6.0,AUTOMATIC,rear wheel drive,2.0,Luxury,Midsize,Convertible,23,17,190,2000
9315,GMC,Sierra 1500,2015,flex-fuel (unleaded/E85),285.0,6.0,AUTOMATIC,four wheel drive,4.0,Flex Fuel,Large,Crew Cab Pickup,22,17,549,38540
7476,Volkswagen,Passat,2016,regular unleaded,170.0,4.0,AUTOMATIC,front wheel drive,4.0,NaN,Midsize,Sedan,38,25,873,24750
6914,Lincoln,MKZ,2017,premium unleaded (recommended),245.0,4.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Sedan,28,20,61,41400
27,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
7283,Lexus,NX 300h,2015,regular unleaded,194.0,4.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Luxury,Hybrid",Midsize,4dr SUV,30,33,454,41310
7736,Chrysler,Prowler,2001,premium unleaded (required),253.0,6.0,AUTOMATIC,rear wheel drive,2.0,High-Performance,Compact,Convertible,21,15,1013,44625
2725,Mercedes-Benz,CLS-Class,2015,premium unleaded (required),329.0,6.0,AUTOMATIC,all wheel drive,4.0,"Luxury,Performance",Midsize,Sedan,28,20,617,68490
4648,Ferrari,F430,2007,premium unleaded (required),483.0,8.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,16,11,2774,211525
4660,Ford,Festiva,1991,regular unleaded,63.0,4.0,MANUAL,front wheel drive,2.0,Hatchback,Compact,2dr Hatchback,38,30,5657,2000

Выводим статистику по числовым показателям

[pandas.DataFrame.describe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)

* count - количество наблюдений, отличных от NA/нулевых.
* max - максимум значений в объекте.
* min - минимум значений в объекте.
* mean- среднее значение.
* std - стандартное отклонение наблюдений.
* select_dtypes - подмножество DataFrame, включающее/исключающее столбцы в зависимости от их типа d.

Процентиль — значение, которое заданная случайная величина не превышает с фиксированной вероятностью, заданной в процентах.
Для числовых данных индекс результата будет включать count, mean, std, min, maxа также нижний 50и верхний процентили. По умолчанию нижний процентиль равен 25, а верхний процентиль равен 75. Процентиль 50аналогичен медиане.

In [11]:
data.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

In [12]:
# статистика по столбцам с текстовыми занчениями
data.describe(include="O")

,Make,Model,Engine Fuel Type,Transmission Type,Driven_Wheels,Market Category,Vehicle Size,Vehicle Style
count,11914,11914,11911,11914,11914,8172,11914,11914
unique,48,915,10,5,4,71,3,16
top,Chevrolet,Silverado 1500,regular unleaded,AUTOMATIC,front wheel drive,Crossover,Compact,Sedan
freq,1123,156,7172,8266,4787,1110,4764,3048

[pandas.DataFrame.groupby](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)


as_index bool, по умолчанию True - Возвращает объект с групповыми метками в качестве индекса. Актуально только для ввода DataFrame.

In [13]:
data.groupby(by=['Make'],as_index=False).mean(numeric_only=True)

,Make,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
0,Acura,2010.063492,244.797619,5.333333,3.619048,28.111111,19.940476,204.0,3.488759e+04
1,Alfa Romeo,2015.400000,237.000000,4.000000,2.000000,34.000000,24.000000,113.0,6.160000e+04
2,Aston Martin,2013.021505,484.322581,10.623656,2.150538,18.892473,12.526882,259.0,1.979104e+05
3,Audi,2012.231707,277.695122,5.557927,3.469512,28.823171,19.585366,3105.0,5.345211e+04
4,BMW,2014.347305,326.907186,5.958084,3.161677,29.245509,20.739521,3916.0,6.154676e+04
5,Bentley,2011.702703,533.851351,9.729730,2.675676,18.905405,11.554054,520.0,2.471693e+05
6,Bugatti,2008.333333,1001.000000,16.000000,2.000000,14.000000,8.000000,820.0,1.757224e+06
7,Buick,2010.005102,219.244898,5.316327,3.836735,26.948980,18.704082,155.0,2.820661e+04
8,Cadillac,2013.151134,332.309824,6.433249,3.602015,25.236776,17.355164,1624.0,5.623132e+04
9,Chevrolet,2010.087266,246.972247,5.908118,3.381122,25.815672,19.021371,1385.0,2.835039e+04
10,Chrysler,2008.459893,229.139037,5.593583,3.625668,26.368984,17.759358,1013.0,2.672296e+04
11,Dodge,2005.440895,244.415335,6.258786,3.210863,22.345048,16.065495,1851.0,2.239006e+04
12,FIAT,2016.032258,143.559322,3.806452,2.903226,37.338710,30.645161,819.0,2.267024e+04
13,Ferrari,2007.521739,511.956522,9.797101,2.000000,15.724638,10.565217,2774.0,2.382188e+05
14,Ford,2009.741203,243.097926,5.914869,3.383655,24.006810,17.960272,5657.0,2.739927e+04
15,GMC,2009.126214,259.844660,6.454369,3.495146,21.403883,15.813592,549.0,3.049330e+04
16,Genesis,2017.000000,347.333333,6.666667,4.000000,25.333333,16.333333,21.0,4.661667e+04
17,HUMMER,2009.352941,261.235294,6.058824,4.000000,17.294118,13.529412,130.0,3.646441e+04
18,Honda,2013.418708,195.749441,4.659243,3.536748,32.574610,25.443207,2202.0,2.667434e+04
19,Hyundai,2012.696370,201.917492,4.666667,3.498350,30.392739,22.343234,1439.0,2.459704e+04
20,Infiniti,2010.960606,310.066667,6.151515,3.545455,24.778788,17.827273,190.0,4.239421e+04
21,Kia,2013.614719,206.827434,4.588745,3.939394,30.653680,23.848485,1720.0,2.531017e+04
22,Lamborghini,2012.730769,614.076923,10.884615,2.000000,18.019231,11.519231,1158.0,3.315673e+05
23,Land Rover,2012.671329,322.097902,6.125874,3.790210,22.125874,16.230769,258.0,6.782322e+04
24,Lexus,2011.623762,277.415842,6.247525,3.712871,25.876238,20.311881,454.0,4.754907e+04
25,Lincoln,2011.573171,284.910256,6.073171,3.853659,24.487805,17.890244,61.0,4.283983e+04
26,Lotus,2010.827586,275.965517,5.241379,2.000000,26.551724,18.758621,613.0,6.918828e+04
27,Maserati,2012.775862,420.793103,7.344828,2.793103,20.293103,13.327586,238.0,1.142077e+05
28,Maybach,2010.937500,590.500000,12.000000,4.000000,16.000000,10.000000,67.0,5.462219e+05
29,Mazda,2008.364066,171.992908,4.615385,3.460993,27.851064,21.245863,586.0,2.003938e+04
30,McLaren,2014.200000,610.400000,8.000000,2.000000,22.200000,15.600000,416.0,2.398050e+05
31,Mercedes-Benz,2010.515581,350.181818,6.711048,3.351275,24.830028,18.181303,617.0,7.147623e+04
32,Mitsubishi,2009.164319,173.429245,4.680952,3.596244,27.544601,21.910798,436.0,2.124054e+04
33,Nissan,2012.403226,239.921533,5.336918,3.433692,27.799283,21.874552,2009.0,2.858343e+04
34,Oldsmobile,1997.613333,177.466667,5.573333,3.573333,26.233333,17.606667,26.0,1.154254e+04
35,Plymouth,1995.463415,131.560976,4.390244,3.207317,27.963415,20.792683,535.0,3.122902e+03
36,Pontiac,2003.102151,190.295699,5.483871,3.193548,27.069892,18.682796,210.0,1.932155e+04
37,Porsche,2013.382353,392.794118,6.132353,2.647059,25.367647,17.470588,1715.0,1.016224e+05
38,Rolls-Royce,2012.516129,487.548387,11.870968,3.290323,19.129032,11.838710,86.0,3.511306e+05
39,Saab,2006.081081,220.522523,4.540541,3.477477,26.351351,17.765766,376.0,2.741350e+04
40,Scion,2013.416667,154.433333,4.000000,3.000000,32.300000,25.316667,105.0,1.993250e+04
41,Spyker,2009.000000,400.000000,8.000000,2.000000,18.000000,13.000000,2.0,2.133233e+05
42,Subaru,2011.246094,197.308594,4.367188,3.773438,28.683594,21.789062,640.0,2.482750e+04
43,Suzuki,2006.310541,160.287749,4.547009,3.823362,26.034188,19.914530,481.0,1.790721e+04
44,Tesla,2015.277778,NaN,0.000000,4.000000,98.944444,94.111111,1391.0,8.525556e+04
45,Toyota,2012.544236,236.147849,5.597315,3.592493,26.453083,21.554960,2031.0,2.903002e+04
46,Volkswagen,2012.812114,189.757726,4.365217,3.222497,32.128554,23.580964,873.0,2.810238e+04
47,Volvo,2008.060498,230.971530,4.722420,3.914591,27.202847,19.583630,870.0,2.854116e+04

In [14]:
data.groupby(by=['Year'],as_index=True).mean(numeric_only=True)

,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
Year,,,,,,,
1990,141.130081,5.292683,2.967480,23.073171,17.089431,1456.048780,2020.203252
1991,147.789474,5.717105,2.828947,22.151316,16.282895,1457.592105,2080.657895
1992,151.395480,5.350282,2.836158,24.050847,17.887006,1387.960452,2077.740113
1993,155.583732,5.341346,2.832536,24.210526,18.062201,1281.344498,2187.325359
1994,157.153374,5.395062,2.957055,23.865031,17.656442,1268.049080,2312.030675
1995,174.666667,5.522388,2.822222,23.229630,17.059259,1733.940741,2606.777778
1996,173.580153,5.312977,2.847328,23.725191,17.572519,1879.068702,2497.366412
1997,184.868571,5.680000,2.702857,22.308571,16.485714,1941.971429,3105.211429
1998,190.051948,6.000000,2.746753,21.850649,16.084416,1847.980519,2975.597403
1999,188.700000,6.025000,3.200000,22.975000,16.866667,1586.375000,3096.158333
2000,183.457627,5.652542,3.305085,24.042373,17.805085,1057.161017,3166.669492
2001,194.130952,5.702381,3.184524,23.708333,17.726190,1204.851190,41500.666667
2002,195.775610,5.790244,3.204878,22.765854,16.829268,1419.400000,33744.156098
2003,206.079832,5.941176,3.189076,22.735294,16.567227,1395.012605,39774.063025
2004,214.914894,6.017021,3.361702,23.148936,16.740426,1361.000000,36107.336170
2005,218.507246,5.915493,3.511737,23.586854,17.103286,1297.492958,36746.971831
2006,229.770732,5.892683,3.541463,23.424390,16.912195,1215.156098,32056.468293
2007,251.837681,6.394203,3.455072,21.939130,15.881159,1171.652174,34974.194203
2008,255.819484,6.108883,3.346705,22.988539,16.555874,1357.343840,54138.916905
2009,251.664908,5.870968,3.456464,23.860158,17.335092,1487.817942,49838.559367
2010,249.436242,5.935154,3.550336,24.144295,17.614094,1303.080537,50642.496644
2011,262.817544,5.939286,3.642105,25.175439,18.656140,1102.596491,57548.178947
2012,265.594315,5.826425,3.483204,26.472868,19.441860,992.689922,59516.235142
2013,267.085165,5.617486,3.501370,27.754098,20.713115,1261.043716,48698.502732
2014,291.772021,5.908163,3.312394,28.045840,21.480475,1325.235993,63226.363328
2015,270.965181,5.466790,3.547005,29.000000,21.467742,1695.047005,46794.461290
2016,273.768007,5.421541,3.607342,29.202133,21.740844,1717.722299,47220.743162
2017,274.615012,5.419219,3.659472,28.577338,21.324341,1894.409472,42191.534173