# Домашнее задание
1. Загрузить выборку `car.csv`
2. В качестве упражнения выведите на экран название (Make) марки и (Model) модель входит в интервал год выпуска (Year) с 2013 по 2015
3. Выводим первый и третий столбцы, сначала по отдельности, потом вместе.
4. Вывести 10 первых строк, вывести 23 случайных строк.
5. Вывести статистику по числовым показателям
6. Сгрупировать данные по столбцу Make, Year

In [1]:
import pandas as pd
import numpy as np

__Загрузить выборку car.csv__

In [2]:
data=pd.read_csv('../dataset/car.csv', delimiter=',')
# data=pd.read_csv('../dataset/car.csv', delimiter=',').dropna()
# data = data.drop(['Market Category'], axis=1)

In [3]:
data['Market Category'] = data['Market Category'].str.replace('Hatchback', '')
data['Market Category'] = data['Market Category'].str.replace('High-Performance', '')
data['Market Category'] = data['Market Category'].str.replace('Performance', '')
data['Market Category'] = data['Market Category'].str.replace('Crossover', '')
data['Market Category'] = data['Market Category'].str.replace('Factory Tuner', '')
data['Market Category'] = data['Market Category'].str.replace(',,', ',')
# data['Market Category'] = data['Market Category'].str[:-1] if data['Market Category'].str.endswith(',') else data['Market Category']
data

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,",Luxury,",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,",Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,",Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,",Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,",Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [4]:
data.shape

(11914, 16)

In [5]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

__В качестве упражнения выведите на экран название (Make) марки и (Model) модель входит в интервал год выпуска (Year) с 2013 по 2015__

In [6]:
# фильтруем данные по условию года выпуска
filtered_data = data[(data['Year'] >= 2013) & (data['Year'] <= 2015)]
# выбираем только столбцы "Make" и "Model"
filtered_data[['Make', 'Model']]

        Make     Model
9        BMW  1 Series
10       BMW  1 Series
11       BMW  1 Series
12       BMW  1 Series
13       BMW  1 Series
...      ...       ...
11896    BMW        Z4
11897    BMW        Z4
11898    BMW        Z4
11899    BMW        Z4
11912  Acura       ZDX

[3125 rows x 2 columns]

__Выводим первый и третий столбцы, сначала по отдельности, потом вместе.__

In [7]:
data.iloc[:,1]

0        1 Series M
1          1 Series
2          1 Series
3          1 Series
4          1 Series
            ...
11909           ZDX
11910           ZDX
11911           ZDX
11912           ZDX
11913        Zephyr
Name: Model, Length: 11914, dtype: object

In [8]:
data.iloc[:,3]

0           premium unleaded (required)
1           premium unleaded (required)
2           premium unleaded (required)
3           premium unleaded (required)
4           premium unleaded (required)
                      ...
11909       premium unleaded (required)
11910       premium unleaded (required)
11911       premium unleaded (required)
11912    premium unleaded (recommended)
11913                  regular unleaded
Name: Engine Fuel Type, Length: 11914, dtype: object

In [9]:
data.iloc[:,[1,3]]

            Model                Engine Fuel Type
0      1 Series M     premium unleaded (required)
1        1 Series     premium unleaded (required)
2        1 Series     premium unleaded (required)
3        1 Series     premium unleaded (required)
4        1 Series     premium unleaded (required)
...           ...                             ...
11909         ZDX     premium unleaded (required)
11910         ZDX     premium unleaded (required)
11911         ZDX     premium unleaded (required)
11912         ZDX  premium unleaded (recommended)
11913      Zephyr                regular unleaded

[11914 rows x 2 columns]

Вывести 10 первых строк, вывести 23 случайных строк.

In [10]:
data.iloc[:10,:]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,",Luxury,",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
5,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Coupe,28,18,3916,31200
6,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Convertible,26,17,3916,44100
7,BMW,1 Series,2012,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,",Compact,Coupe,28,20,3916,39300
8,BMW,1 Series,2012,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,36900
9,BMW,1 Series,2013,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,27,18,3916,37200

In [11]:
randIdx = np.random.randint(data.shape[0], size=25)
data.iloc[randIdx,:]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
5198,Pontiac,G6,2009,regular unleaded,252.0,6.0,AUTOMATIC,front wheel drive,2.0,,Midsize,Coupe,26,17,210,28480
4718,Honda,Fit,2016,regular unleaded,130.0,4.0,MANUAL,front wheel drive,4.0,,Compact,4dr Hatchback,37,29,2202,15890
7578,Toyota,Pickup,1994,regular unleaded,150.0,6.0,MANUAL,four wheel drive,2.0,NaN,Compact,Extended Cab Pickup,17,14,2031,2423
403,Mazda,3,2017,regular unleaded,184.0,4.0,AUTOMATIC,front wheel drive,4.0,",",Compact,4dr Hatchback,35,26,586,24945
4120,Cadillac,Escalade ESV,2016,premium unleaded (recommended),420.0,8.0,AUTOMATIC,four wheel drive,4.0,"Luxury,",Large,4dr SUV,21,15,1624,94950
11039,Toyota,Tundra,2017,regular unleaded,381.0,8.0,AUTOMATIC,rear wheel drive,4.0,NaN,Large,Extended Cab Pickup,18,13,2031,33100
9651,Buick,Skylark,1996,regular unleaded,150.0,4.0,AUTOMATIC,front wheel drive,2.0,NaN,Midsize,Coupe,29,19,155,2000
808,Saab,9-3 Griffin,2012,flex-fuel (premium unleaded recommended/E85),220.0,4.0,MANUAL,front wheel drive,2.0,"Flex Fuel,Luxury",Compact,Convertible,33,20,376,39490
4914,Ford,Freestar,2005,regular unleaded,NaN,6.0,AUTOMATIC,front wheel drive,4.0,NaN,Midsize,Passenger Minivan,22,16,5657,28030
8908,Volvo,S60,2016,regular unleaded,325.0,6.0,AUTOMATIC,all wheel drive,4.0,"Luxury,",Midsize,Sedan,27,18,870,47700
5254,Hyundai,Genesis Coupe,2016,premium unleaded (recommended),348.0,6.0,MANUAL,rear wheel drive,2.0,,Midsize,Coupe,24,17,1439,26950
10275,Ford,Taurus X,2008,regular unleaded,260.0,6.0,AUTOMATIC,front wheel drive,4.0,,Large,Wagon,24,16,5657,27030
8215,Dodge,Ram Wagon,2000,regular unleaded,175.0,6.0,AUTOMATIC,rear wheel drive,3.0,NaN,Compact,Passenger Van,15,13,1851,2326
11361,Nissan,Versa,2017,regular unleaded,109.0,4.0,AUTOMATIC,front wheel drive,4.0,NaN,Compact,Sedan,39,31,2009,15720
9247,Toyota,Sienna,2017,regular unleaded,296.0,6.0,AUTOMATIC,front wheel drive,4.0,NaN,Large,Passenger Minivan,27,19,2031,36110
1827,Volkswagen,Beetle Convertible,2015,regular unleaded,170.0,4.0,AUTOMATIC,front wheel drive,2.0,NaN,Compact,Convertible,32,24,873,29595
5166,Infiniti,G37,2009,premium unleaded (required),325.0,6.0,AUTOMATIC,rear wheel drive,2.0,"Luxury,",Midsize,Convertible,25,17,190,43850
590,FIAT,500X,2016,regular unleaded,180.0,4.0,AUTOMATIC,front wheel drive,4.0,,Compact,4dr SUV,31,22,819,27335
2822,Plymouth,Colt,1992,regular unleaded,92.0,4.0,MANUAL,front wheel drive,2.0,,Compact,2dr Hatchback,32,25,535,2000
998,Porsche,944,1990,regular unleaded,208.0,4.0,MANUAL,rear wheel drive,2.0,",Luxury,",Compact,2dr Hatchback,24,15,1715,2667
5637,Volkswagen,GTI,2013,premium unleaded (recommended),200.0,4.0,MANUAL,front wheel drive,4.0,",",Compact,4dr Hatchback,31,21,873,29695
910,Saab,900,1998,regular unleaded,185.0,4.0,MANUAL,front wheel drive,2.0,",Luxury,",Compact,2dr Hatchback,24,18,376,2000
2999,Chevrolet,Corvette,2016,premium unleaded (required),650.0,8.0,MANUAL,rear wheel drive,2.0,",",Compact,Convertible,22,15,1385,92345
4276,Infiniti,EX35,2009,premium unleaded (recommended),297.0,6.0,AUTOMATIC,rear wheel drive,4.0,",Luxury",Midsize,4dr SUV,24,17,190,33800
9484,Chevrolet,Silverado 1500 Hybrid,2011,regular unleaded,332.0,8.0,AUTOMATIC,rear wheel drive,4.0,Hybrid,Large,Crew Cab Pickup,23,20,1385,38725

Выводим статистику по числовым показателям

[pandas.DataFrame.describe](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)

* count - количество наблюдений, отличных от NA/нулевых.
* max - максимум значений в объекте.
* min - минимум значений в объекте.
* mean- среднее значение.
* std - стандартное отклонение наблюдений.
* select_dtypes - подмножество DataFrame, включающее/исключающее столбцы в зависимости от их типа d.

Процентиль — значение, которое заданная случайная величина не превышает с фиксированной вероятностью, заданной в процентах.
Для числовых данных индекс результата будет включать count, mean, std, min, maxа также нижний 50и верхний процентили. По умолчанию нижний процентиль равен 25, а верхний процентиль равен 75. Процентиль 50аналогичен медиане.

In [12]:
data.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

* В столбцах "Engine HP", "Engine Cylinders", "Number of Doors" есть пропуски данных, потому что count меньше чем размер выборки
* В столбце Engine Cylinders есть значения 0.0, что также можно считать отсутствием данных

In [13]:
# статистика по столбцам с текстовыми занчениями

data.describe(include="O")

,Make,Model,Engine Fuel Type,Transmission Type,Driven_Wheels,Market Category,Vehicle Size,Vehicle Style
count,11914,11914,11911,11914,11914,8172,11914,11914
unique,48,915,10,5,4,31,3,16
top,Chevrolet,Silverado 1500,regular unleaded,AUTOMATIC,front wheel drive,,Compact,Sedan
freq,1123,156,7172,8266,4787,2551,4764,3048

[pandas.DataFrame.groupby](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html)


as_index bool, по умолчанию True - Возвращает объект с групповыми метками в качестве индекса. Актуально только для ввода DataFrame.

In [21]:
data.groupby(by=['Make'],as_index=False).min(numeric_only=True)['MSRP'].mean()

72609.27083333333

In [15]:
data.groupby(by=['Make'],as_index=False).max(numeric_only=True)

,Make,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
0,Acura,2017,573.0,6.0,4.0,38,39,204,156000
1,Alfa Romeo,2016,237.0,4.0,2.0,34,24,113,68400
2,Aston Martin,2016,568.0,12.0,4.0,22,14,259,320695
3,Audi,2017,610.0,12.0,4.0,354,31,3105,199900
4,BMW,2017,600.0,12.0,4.0,111,137,3916,141200
5,Bentley,2016,631.0,12.0,4.0,25,15,520,363000
6,Bugatti,2009,1001.0,16.0,2.0,14,8,820,2065902
7,Buick,2017,310.0,8.0,4.0,36,28,155,49625
8,Cadillac,2017,640.0,8.0,4.0,33,22,1624,104215
9,Chevrolet,2017,650.0,8.0,4.0,110,128,1385,92395
10,Chrysler,2017,385.0,8.0,4.0,36,23,1013,49470
11,Dodge,2017,707.0,10.0,4.0,41,28,1851,120395
12,FIAT,2017,180.0,4.0,4.0,108,122,819,31800
13,Ferrari,2015,731.0,12.0,2.0,23,16,2774,643330
14,Ford,2017,662.0,8.0,4.0,99,110,5657,149995
15,GMC,2017,420.0,8.0,4.0,32,22,549,71665
16,Genesis,2017,420.0,8.0,4.0,28,18,21,54550
17,HUMMER,2010,300.0,8.0,4.0,18,14,130,43130
18,Honda,2017,280.0,6.0,4.0,105,132,2202,47070
19,Hyundai,2017,429.0,8.0,4.0,45,40,1439,68750
20,Infiniti,2017,420.0,8.0,4.0,36,29,190,88850
21,Kia,2017,420.0,8.0,4.0,92,120,1720,61900
22,Lamborghini,2016,750.0,12.0,2.0,21,15,1158,1500000
23,Land Rover,2017,550.0,8.0,4.0,30,22,258,199495
24,Lexus,2017,552.0,10.0,4.0,40,43,454,375000
25,Lincoln,2017,380.0,8.0,4.0,39,41,61,76650
26,Lotus,2017,400.0,8.0,2.0,39,21,613,93225
27,Maserati,2017,523.0,8.0,4.0,25,17,238,182009
28,Maybach,2012,631.0,12.0,4.0,16,10,67,1382750
29,Mazda,2017,274.0,6.0,4.0,41,34,586,44015
30,McLaren,2016,641.0,8.0,2.0,23,16,416,280225
31,Mercedes-Benz,2017,641.0,12.0,4.0,82,85,617,495000
32,Mitsubishi,2017,320.0,8.0,4.0,102,126,436,38995
33,Nissan,2017,600.0,8.0,4.0,101,126,2009,149990
34,Oldsmobile,2004,275.0,8.0,4.0,31,22,26,36795
35,Plymouth,2001,253.0,6.0,4.0,36,28,535,44625
36,Pontiac,2010,415.0,8.0,4.0,37,27,210,37610
37,Porsche,2017,605.0,10.0,4.0,30,21,1715,440000
38,Rolls-Royce,2016,624.0,12.0,4.0,21,13,86,492425
39,Saab,2012,390.0,8.0,4.0,33,21,376,51330
40,Scion,2016,200.0,4.0,4.0,42,36,105,31090
41,Spyker,2009,400.0,8.0,2.0,18,13,2,219990
42,Subaru,2017,305.0,6.0,4.0,38,30,640,39995
43,Suzuki,2013,261.0,6.0,4.0,39,33,481,31749
44,Tesla,2016,NaN,0.0,4.0,107,102,1391,134500
45,Toyota,2017,381.0,8.0,4.0,74,78,2031,84325
46,Volkswagen,2017,444.0,12.0,4.0,105,126,873,101300
47,Volvo,2017,345.0,6.0,4.0,38,26,870,65700

In [16]:
data.groupby(by=['Transmission Type'],as_index=True).min(numeric_only=True)

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
Transmission Type,,,,,,,,
AUTOMATED_MANUAL,2002,120.0,4.0,2.0,12,7,113,19050
AUTOMATIC,1990,73.0,3.0,2.0,12,9,21,2000
DIRECT_DRIVE,2012,66.0,0.0,2.0,43,47,436,22995
MANUAL,1990,55.0,3.0,2.0,12,8,2,2000
UNKNOWN,1991,100.0,4.0,2.0,17,12,26,2000

In [17]:
data.groupby(by=['Transmission Type'],as_index=True).max(numeric_only=True)

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
Transmission Type,,,,,,,,
AUTOMATED_MANUAL,2017,1001.0,16.0,4.0,354,42,5657,2065902
AUTOMATIC,2017,707.0,12.0,4.0,53,58,5657,1382750
DIRECT_DRIVE,2017,200.0,4.0,4.0,111,137,5657,134500
MANUAL,2017,707.0,12.0,4.0,46,36,5657,440000
UNKNOWN,2000,305.0,8.0,4.0,29,21,1851,9567

In [18]:
data.groupby(by=['Engine Cylinders'],as_index=True).min(numeric_only=True)

,Year,Engine HP,Number of Doors,highway MPG,city mpg,Popularity,MSRP
Engine Cylinders,,,,,,,
0.0,2013,140.0,2.0,74,78,617,25120
3.0,1992,55.0,2.0,29,24,436,2000
4.0,1990,62.0,2.0,15,14,26,2000
5.0,1990,121.0,2.0,18,13,130,2000
6.0,1990,116.0,2.0,13,11,21,2000
8.0,1990,125.0,2.0,12,9,2,2000
10.0,2004,310.0,2.0,15,9,454,68340
12.0,1992,322.0,2.0,12,7,67,2960
16.0,2008,1001.0,2.0,14,8,820,1500000

In [19]:
data.groupby(by=['Engine Cylinders'],as_index=True).max(numeric_only=True)

,Year,Engine HP,Number of Doors,highway MPG,city mpg,Popularity,MSRP
Engine Cylinders,,,,,,,
0.0,2017,177.0,4.0,111,137,5657,134500
3.0,2017,123.0,4.0,44,37,5657,18175
4.0,2017,375.0,4.0,354,58,5657,74995
5.0,2016,360.0,4.0,33,24,3105,57200
6.0,2017,600.0,4.0,39,32,5657,200400
8.0,2017,707.0,4.0,29,20,5657,495000
10.0,2017,645.0,4.0,22,15,3105,440000
12.0,2017,750.0,4.0,22,14,3916,1500000
16.0,2009,1001.0,2.0,14,8,820,2065902

In [20]:
data.groupby(by=['Market Category'],as_index=False).min(numeric_only=True)

,Market Category,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
0,,1990,55.0,0.0,2.0,18,13,26,2000
1,",",1991,140.0,4.0,2.0,15,12,155,2000
2,",,",2015,211.0,4.0,4.0,29,25,2009,28020
3,",Diesel",2009,150.0,4.0,2.0,25,17,873,22345
4,",Exotic,Luxury,",2017,345.0,6.0,4.0,19,14,238,72000
5,",Flex Fuel",2010,160.0,4.0,4.0,21,15,155,18960
6,",Flex Fuel,",2015,280.0,4.0,4.0,23,17,5657,33000
7,",Flex Fuel,Luxury",2010,220.0,4.0,4.0,16,13,130,30915
8,",Flex Fuel,Luxury,",2011,403.0,8.0,4.0,18,13,1624,67250
9,",Hybrid",2008,98.0,4.0,2.0,24,20,155,18500
10,",Luxury",1996,140.0,0.0,2.0,14,12,61,2000
11,",Luxury,",1990,160.0,4.0,2.0,13,10,61,2000
12,",Luxury,Diesel",2008,180.0,4.0,4.0,20,15,617,38590
13,",Luxury,Hybrid",2006,134.0,4.0,4.0,19,17,190,31250
14,Diesel,2012,140.0,4.0,2.0,19,14,549,21640
15,"Diesel,Luxury",1990,121.0,4.0,4.0,22,18,258,2000
16,"Exotic,",2001,189.0,0.0,2.0,12,7,2,43995
17,"Exotic,Flex Fuel,Luxury,",2010,552.0,12.0,2.0,17,10,520,181200
18,"Exotic,Luxury",2001,322.0,8.0,2.0,15,10,67,219900
19,"Exotic,Luxury,",2001,252.0,6.0,2.0,14,9,67,69800
20,"Exotic,Luxury,Hybrid",2017,573.0,6.0,2.0,22,21,204,156000
21,Flex Fuel,1999,120.0,4.0,2.0,15,11,155,2055
22,"Flex Fuel,",2012,184.0,4.0,4.0,22,15,155,23995
23,"Flex Fuel,Diesel",2015,275.0,6.0,3.0,19,14,5657,35920
24,"Flex Fuel,Hybrid",2015,182.0,4.0,4.0,28,18,155,33635
25,"Flex Fuel,Luxury",2009,220.0,4.0,2.0,16,13,61,28900
26,"Flex Fuel,Luxury,",2014,321.0,6.0,2.0,19,13,258,41340
27,Hybrid,2008,110.0,4.0,4.0,22,20,549,23640
28,Luxury,1990,108.0,4.0,2.0,14,10,61,2000
29,"Luxury,",1990,162.0,4.0,2.0,16,11,21,2000
30,"Luxury,Hybrid",2010,111.0,4.0,4.0,23,19,61,28900